import Header from '@/components/Header';
import Head from 'next/head';
import { HiOutlineHeart } from 'react-icons/hi2';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-gray-100 text-base'>
        <div className='pt-6'>
          <Header />
          <div className='w-full lg:max-w-7xl mx-auto'>
            <div className='mt-12 text-5xl font-bold text-center leading-normal'>
              A supporter is worth a<br />
              thousand followers.
            </div>
            <div className='mt-8 text-xl text-center'>
              Accept donations. Start a membership. Sell anything you like.
              <br />
              It's easier than you think.
            </div>
            <div className='flex mt-8 rounded-full bg-white border-gray-200 max-w-xl mx-auto text-2xl font-semibold items-center'>
              <span className='pl-6 py-4'>kofe.com/</span>
              <input type='text' className='outline-none w-64' placeholder='yourname' />
              <button className='text-xl bg-yellow-300 rounded-full px-4 py-3 ml-auto my-2.5 mr-3 font-bold'>Start my page</button>
            </div>
            <div className='mx-auto text-center mt-4'>It's free, and takes less than a minute.</div>
            <div className='w-full lg:max-w-[970px] mx-auto pb-10'>
              <div className='flex mt-8 gap-4 font-semibold place-content-center'>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Video Creators
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Artists
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Writers
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Musicians
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Developers
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Gaming
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Podcasters
                </a>
                <a className='px-4 py-2 btn-hover-bg relative' href=''>
                  Community
                </a>
              </div>
              <div className='flex overflow-auto transparent-scrollbar mt-6 gap-12 place-content-center'>
                <a href='#' className='w-[200px] block gap-6 mx-6 md:mx-0'>
                  <div className='w-[200px] h-[200px] overflow-hidden'>
                    <img src='/c1.jpg' alt='' className='w-full h-full object-cover transform hover:scale-105 duration-300' />
                  </div>
                  <div className='flex flex-col flex-wrap featured-details justify-between'>
                    <div className='mt-3 text-base leading-6 line-clamp-3'>
                      <b>PriorAttire</b> is creating YouTube videos on historical fashions, dressmaking etc.
                    </div>
                    <div className='mt-3 flex items-center text-base gap-2'>
                      <HiOutlineHeart width={16} height={16} />
                      435 Supporters
                    </div>
                  </div>
                </a>
                <a href='#' className='w-[200px] block gap-6 mx-6 md:mx-0'>
                  <div className='w-[200px] h-[200px] overflow-hidden'>
                    <img src='/c2.jpg' alt='' className='w-full h-full object-cover transform hover:scale-105 duration-300' />
                  </div>
                  <div className='flex flex-col flex-wrap featured-details justify-between'>
                    <div className='mt-3 text-base leading-6 line-clamp-3 max-w-[200px]'>
                      <b>HandyMumLin</b> is Sewing video maker
                    </div>
                    <div className='mt-3 flex items-center text-base gap-2'>
                      <HiOutlineHeart width={16} height={16} />
                      548 Supporters
                    </div>
                  </div>
                </a>
                <a href='#' className='w-[200px] block gap-6 mx-6 md:mx-0'>
                  <div className='w-[200px] h-[200px] overflow-hidden'>
                    <img src='/c3.jpg' alt='' className='w-full h-full object-cover transform hover:scale-105 duration-300' />
                  </div>
                  <div className='flex flex-col flex-wrap featured-details justify-between'>
                    <div className='mt-3 text-base leading-6 line-clamp-3 max-w-[200px]'>
                      <b>Kevin Wilson</b> is telling stories over a cup of chai
                    </div>
                    <div className='mt-3 flex items-center text-base gap-2'>
                      <HiOutlineHeart width={16} height={16} />
                      1252 Supporters
                    </div>
                  </div>
                </a>
                <a href='#' className='w-[200px] block gap-6 mx-6 md:mx-0'>
                  <div className='w-[200px] h-[200px] overflow-hidden'>
                    <img src='/c4.jpg' alt='' className='w-full h-full object-cover transform hover:scale-105 duration-300' />
                  </div>
                  <div className='flex flex-col flex-wrap featured-details justify-between'>
                    <div className='mt-3 text-base leading-6 line-clamp-3 max-w-[200px]'>
                      <b>Feli from Germany</b> is creating YouTube videos
                    </div>
                    <div className='mt-3 flex items-center text-base gap-2'>
                      <HiOutlineHeart width={16} height={16} />
                      618 Supporters
                    </div>
                  </div>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
